language: python

python:
  - "2.7"
  
sudo: required

before_install:
  - pip install pytest


env: DEPS="numpy scipy matplotlib pandas statsmodels"

install: 
  - pip install -r requirements.txt   

    
script:
  - pytest test/test.py
  
deploy:
  provider: pypi
  distributions: sdist
  user: "paulinkenbrandt"
  password:
    secure: "hdRtHAJr0PNtlbJhpynPtzC3fak/Qfp+hVqTqACmaLn5ZMP9yn08Lz+Y9KM6K2CI7TXXkt+TmAntGYiBcIO2bc1h+zmSbvm/6JfZ0fKrht1oZQFwrpAHw9HXAGwxznQPU8gteKJgMjXoNZNp/5Dw6/nX/LzBOULO7Jz3UiUFsZMftb9JsGLrF4359xdBn0buwrKnbplapdqs6sbPS3Ga9lx/VenRNcrRW12LpgZggaZFPSACZcflOfGtLSzneWvuFHJWaZfyklpN62PBx692I5iI4nR9DgVjno3LjeJ/r6O1B9Hav5xjd8np0fu6ETwVd8llSSY7jkvX0vI4b4dD4BjjIG+P6MqkNh2TJ6jQ4z6ia2BSl/FeXzwW9+pfqg0YMKWywVhlkSqu/QjORD8Y+KZkDRZv5K5k+1JtMYLfn4sIUYmowq0eHEtHDa5voYGT6Y+Wdk91FwWZfjcghq4fHyN+VckMnz2IhVlva4ft05STod80xfKr5Ph8/qhU3kkzda7wPoHRItLhXizW8ix0Ui1lJOLXTe7CtAhzUqhkC0y9sxPuy7wSEbvspWMM3Mkf0nsvLyWih7TISTmtO0sO9A9IQP2vEqJqCwvRieoe9VJSBBDkcj8RQ7K5u6eFRCgoyWO1U2zVa8/DdXhzO4KV7L1FhGf57+K5lyjv3V9DvUc="
