# Config file for automatic testing at travis-ci.org

language: python
python:
  - "2.7"
  - "3.3"

install:
  - pip install .
  - pip install docopt querycsv coverage nose nose-cov mock flake8

script:
  - nosetests
after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
