# Config file for automatic testing at travis-ci.org

language: python
python:
  - "2.7"

before_install:
  - pip install codecov
install:
  - pip install pandas numpy xmltodict matplotlib docopt querycsv coverage nose nose-cov mock flake8

script:
  - nosetests --with-coverage
after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
