language: python

python:
  - "2.7"
  
sudo: required

before_install:
  - pip install pytest


env: DEPS="numpy scipy matplotlib pandas statsmodels"

install: 
  - pip install -r requirements.txt   

    
script:
  - python setup.py test
